name: Windows Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '5300a2a461a53b76405db4fcbe6aeb0eea43935d'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
            ${{ env.VCPKG_ROOT }}/buildtrees
          key: vcpkg-windows-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-windows-

      - name: Configure CMake with compile commands
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build Project
        run: cmake --build build --parallel 4

      - name: Run Executable
        working-directory: build/bin/Debug
        run: ./meowstro.exe --test

      - name: Run cppcheck (static analysis)
        run: |
          if (!(Get-Command cppcheck -ErrorAction SilentlyContinue)) {
            choco install cppcheck -y
          }
          # Configure cppcheck with proper include paths and suppress system header warnings
          cppcheck --enable=all --inconclusive --std=c++17 --quiet `
            --suppress=missingIncludeSystem `
            --suppress=missingInclude `
            -I include `
            -I "${{ env.VCPKG_ROOT }}/installed/x64-windows/include" `
            src

      - name: Run clang-tidy (static analysis)
        run: |
          if (!(Get-Command clang-tidy -ErrorAction SilentlyContinue)) {
            choco install llvm -y
          }
          # Use the compilation database that CMake generated
          if (Test-Path "build/compile_commands.json") {
            clang-tidy -p build $(Get-ChildItem -Path src -Filter *.cpp | ForEach-Object { $_.FullName })
          } else {
            Write-Host "No compilation database found, skipping clang-tidy"
          }

      - name: Run ctest (unit tests)
        run: |
          cd build
          ctest --output-on-failure || echo "No tests configured"

      - name: Upload Executable Artifact (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: meowstro-windows
          path: build/bin/Debug/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '5300a2a461a53b76405db4fcbe6aeb0eea43935d'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
            ${{ env.VCPKG_ROOT }}/buildtrees
          key: vcpkg-linux-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-linux-

      - name: Configure CMake with compile commands
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build Project
        run: cmake --build build --parallel $(nproc)

      - name: Run Executable
        working-directory: build/bin/Debug
        run: ./meowstro --test

      - name: Run cppcheck (static analysis)
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --inconclusive --std=c++17 --quiet \
            --suppress=missingIncludeSystem \
            --suppress=missingInclude \
            -I include \
            -I "${{ env.VCPKG_ROOT }}/installed/x64-linux/include" \
            src

      - name: Run clang-tidy (static analysis)
        run: |
          sudo apt-get install -y clang-tidy
          if [ -f "build/compile_commands.json" ]; then
            clang-tidy -p build $(find src -name '*.cpp')
          else
            echo "No compilation database found, skipping clang-tidy"
          fi

      - name: Run ctest (unit tests)
        run: |
          cd build
          ctest --output-on-failure || echo "No tests configured"

      - name: Upload Executable Artifact (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: meowstro-linux
          path: build/bin/Debug/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '5300a2a461a53b76405db4fcbe6aeb0eea43935d'

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
            ${{ env.VCPKG_ROOT }}/buildtrees
          key: vcpkg-macos-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-macos-

      - name: Configure CMake with compile commands
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build Project
        run: cmake --build build --parallel $(sysctl -n hw.logicalcpu)

      - name: Run Executable
        working-directory: build/bin/Debug
        run: ./meowstro --test

      - name: Run cppcheck (static analysis)
        run: |
          brew install cppcheck
          cppcheck --enable=all --inconclusive --std=c++17 --quiet \
            --suppress=missingIncludeSystem \
            --suppress=missingInclude \
            -I include \
            -I "${{ env.VCPKG_ROOT }}/installed/x64-osx/include" \
            src

      - name: Run clang-tidy (static analysis)
        run: |
          brew install llvm
          if [ -f "build/compile_commands.json" ]; then
            $(brew --prefix llvm)/bin/clang-tidy -p build $(find src -name '*.cpp')
          else
            echo "No compilation database found, skipping clang-tidy"
          fi

      - name: Run ctest (unit tests)
        run: |
          cd build
          ctest --output-on-failure || echo "No tests configured"

      - name: Upload Executable Artifact (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: meowstro-macos
          path: build/bin/Debug/